@baseUrl = 'http://localhost:8080/api/auth'

###
//POST - Cria um usuario
POST {{baseUrl}}
Content-Type: application/json

{
    "name": "Teste http",
    "email": "http@email.com",
    "password": "Teste.123"
}

###
//POST - Login de usuario
POST {{{baseUrl}}}/login
Content-Type: application/json

{
    "email": "http@email.com",
    "password": "Teste.123"
}

###
//GET - 